#!/usr/bin/env python

import sys
import argparse as ap

parser = ap.ArgumentParser(prog='concatenater', conflict_handler='resolve',
                           description="Concatenates all accessions and their associated paths")

input = parser.add_argument_group('Input', '')
input.add_argument('-n', '--name', nargs='+', required=True, help="Sample name (accessions)")
input.add_argument('-i', '--input', nargs='+', required=True, help="Paths to calls")

if len(sys.argv) == 1:
    parser.print_usage()
    sys.exit(1)

args = parser.parse_args()
output = open('paths.txt', 'w')

for index,path in enumerate(args.input):
    output.write("%s=%s\n" % (args.name[index], path))
